import { dev } from '$app/environment';
export const title = "Lauhard Andreas";
export const author = "Lauhard";
export const domain = "lauhard.dev";
export const description = "Personal website of Lauhard Andreas";
export const url = dev ? "http://localhost:5173" : `https://${domain}`;
export const image = `${url}/images/og-image.png`;
export const locale = "en";
export const siteName = domain;
export const twitter = "";
export const github = "";
export const linkedin = "";
export const email = "";
export const phone = "";
export const address = "";
export const city = "";
export const country = "";
export const postalCode = "";
export const blogPostPath = "src/routes/blog/";

